apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-app-cluster
  region: us-east-1

iam:
  withOIDC: true

vpc:
  cidr: "10.0.0.0/16"

managedNodeGroups:
  - name: ng-standard
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 10
    volumeSize: 50
    ssh:
      allow: true
      publicKeyName: my-keypair
