apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../k8s_orchestration.yaml

images:
  - name: myregistry.example.com/my-app
    newName: <REGISTRY_URL>/my-app
    newTag: latest
