graph LR
  subgraph Dev_Workflow[Developer Workflow]
    A[Code Commit & PR] --> B[GitHub Actions CI]
  end

  subgraph CI_Pipeline[CI Pipeline]
    B --> C[Build & Test]
    C --> D[Push Image to ECR]
    D --> E[Trivy Scan]
    E --> F[Update infra/overlays/prod]
    F --> G[Auto-commit Bump to Git]
  end

  subgraph GitOps_CD[Argo CD]
    G --> H[Monitor infra Repo]
    H --> I[Sync to EKS]
    I --> J[Deployment in Kubernetes]
  end

  subgraph EKS_Cluster[EKS Cluster]
    J --> K[Pods + Services]
    J --> L[HPA & Metrics]
  end

  style Dev_Workflow fill:#e0f7fa,stroke:#006064
  style CI_Pipeline fill:#ede7f6,stroke:#4527a0
  style GitOps_CD fill:#f1f8e9,stroke:#33691e
  style EKS_Cluster fill:#fff3e0,stroke:#e65100