name: CI

on:
  push:
    paths:
      - 'app/**'
      - 'infra/**'
  pull_request:
    paths:
      - 'app/**'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
  IMAGE_REPO: my-app

jobs:
  build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push image
        id: image_build
        run: |
          TAG=${{ github.sha }}
          docker buildx build             --platform linux/amd64             --tag ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_REPO }}:$TAG             --push .
          echo "::set-output name=TAG::$TAG"

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.9.4
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ steps.image_build.outputs.TAG }}
          severity: HIGH,CRITICAL

      - name: Update Kustomize image tag
        run: |
          cd infra/overlays/prod
          kustomize edit set image             ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_REPO }}=${{ env.ECR_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ steps.image_build.outputs.TAG }}

      - name: Commit & Push manifests bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: bump image to ${{ steps.image_build.outputs.TAG }}"
          branch: main
          file_pattern: 'infra/overlays/prod/kustomization.yaml'
          author_name: github-actions
          author_email: actions@github.com
